services:
  - type: web
    name: turism-server
    env: node
    plan: free
    buildCommand: pnpm install && pnpm --filter server build
    startCommand: cd apps/server && pnpm start
    envVars:
      - key: PORT
        value: 3001
